### ISSUE TITLE
ERROR in node_modules/ngx-drag-and-drop-lists/directives/dnd-list.d.ts(3,25): error TS2307: Cannot find module 'rxjs/internal/Subject

### ISSUE THREAD

**Issue by kevinjsmith** [misha130/ngx-drag-and-drop-lists#25]
Seeing this error after updating to 1.2.3:
`ERROR in node_modules/ngx-drag-and-drop-lists/directives/dnd-list.d.ts(3,25): error TS2307: Cannot find module 'rxjs/internal/Subject'.`
Changing path to 'rxjs/Subject' in that file and dnd-list.js resolves the issue. Could you please update with this small fix? We are on Angular 5.

**Comment by misha130** [comment]
I had to add rxjs-compat to support the angular 5 and at the same move it to rxjs/Subject.

Could anyone tell me if its optimal maybe to add rxjs 6 to dependencies from dev dependencies?

**Comment by pawkrol** [comment]
So I have been trying to use it in Angular 6 project, and with RxJS v6 the 'rxjs/Subject' does not work again. It must be 'rxjs' alone:
`import { Subject } from 'rxjs'`

**Comment by misha130** [comment]
Install rxjs-compat

**Comment by blackn1ght** [comment]
~Installing rxjs-compat doesn't resolve the issue.  Using Angular 6.~

Scrap this.  I hadn't stopped my build and restarted in VS.

> ./node_modules/ngx-drag-and-drop-lists/directives/dnd-list.js
Module not found: Error: Can't resolve 'rxjs/Subject'

**Comment by adhamankar** [comment]
any plans to upgrade to latest rxjs (angular6+ compatible) version?
